# Generated by Django 6.0 on 2026-03-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signup_app", "0002_alter_all_user_options_alter_all_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="all_user",
            managers=[],
        ),
    ]
