# Generated by Django 6.0 on 2026-03-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup_app", "0003_alter_all_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="all_user",
            options={},
        ),
        migrations.RemoveField(
            model_name="all_user",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="all_user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="all_user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="all_user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="all_user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="all_user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="all_user",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="all_user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="all_user",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="all_user",
            name="fname",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="all_user",
            name="password",
            field=models.CharField(max_length=50),
        ),
    ]
