# Generated by Django 6.0 on 2026-03-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "signup_app",
            "0004_alter_all_user_options_remove_all_user_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="All_user",
        ),
    ]
