# Generated by Django 6.0 on 2026-03-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("post_msg", models.CharField(max_length=100)),
                ("cretaed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
