# Generated by Django 6.0 on 2026-03-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_post",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
