# Generated by Django 6.0 on 2026-04-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_user_post_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Friend_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_friend", models.EmailField(max_length=254)),
                ("target_friend", models.EmailField(max_length=254)),
                ("cretaed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
